spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=templatedb;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false